import { useEffect, useMemo, useRef, useState } from 'react';
import DrawRevealPathEditor from './DrawRevealPathEditor.jsx';
import {
  Activity, AlertTriangle, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, AudioLines, Bot, BrainCircuit,
  Check, CheckCircle2, Clapperboard, Copy, Eye, FileText, Film, Gauge, History, Image as ImageIcon, Inbox,
  Layers3, LoaderCircle, Maximize2, Merge, Minimize2, MoreHorizontal, Palette, PanelLeftClose, PanelLeftOpen,
  PanelRightClose, PanelRightOpen, Play, Plus, Redo2, RefreshCw, Save, Scissors, Send, Sparkles, Square,
  Download, ExternalLink, Search, Trash2, Undo2, Upload, WandSparkles, X, Zap,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { usePersistentState } from './hooks/usePersistentState';
import {
  WORKFLOW_STAGES as STAGES,
  artifactReady as ready,
  bestAvailableView as bestView,
  buildActionInbox,
  getNextAction as nextForScene,
  getSceneHealth as sceneHealth,
} from './workspace-intelligence.mjs';

const VIEWS=['best','script','voice','visual','clip'];
const labels=(c)=>({best:c.bestAvailable,script:c.scriptStage,voice:c.voiceStage,visual:c.visualStage,clip:c.clipStage});
const StageIcon=({stage})=>stage==='script'?<FileText/>:stage==='voice'?<AudioLines/>:stage==='visual'?<ImageIcon/>:<Film/>;
const mediaUrl=(project,scene,kind)=>`/media/${encodeURIComponent(project.id)}/scenes/${encodeURIComponent(scene.id)}/${kind}?v=${encodeURIComponent(project.updatedAt||'current')}`;

function Preview({project,scene,view,c}){
  const actual=view==='best'?bestView(scene):view;
  if(actual==='clip'&&scene.artifacts?.clip)return <video className="director-media" controls preload="metadata" src={mediaUrl(project,scene,'clip')}/>;
  if(actual==='visual'&&scene.artifacts?.visual)return <img className="director-media" src={mediaUrl(project,scene,'visual')} alt={`${c.visual} ${scene.index+1}`}/>;
  if(actual==='voice'&&scene.artifacts?.voice)return <div className="director-voice-card"><span><AudioLines/></span><small>{c.voiceStage}</small><p>{scene.text}</p><audio controls preload="metadata" src={mediaUrl(project,scene,'voice')}/></div>;
  if(actual==='script')return <div className="director-script-card"><span>“</span><p>{scene.text}</p><footer><strong>{String(scene.index+1).padStart(2,'0')}</strong><small>{(scene.durationMs/1000).toFixed(1)} {c.seconds}</small></footer></div>;
  return <div className="director-empty-preview"><span><StageIcon stage={actual}/></span><strong>{labels(c)[actual]}</strong><p>{actual==='visual'&&scene.cache?.image?c.mockVisualReady:c.awaitingStage}</p></div>;
}

function TakeSwitcher({scene,view,onSelect,c}){
  const kind=view==='best'?bestView(scene):view,takes=scene.takes?.[kind]||[];
  if(!['voice','visual','clip'].includes(kind)||!takes.length)return null;
  return <div className="take-switcher"><span>{c.takes}</span><div>{takes.map((take,index)=><button key={take.id} className={scene.selectedTakes?.[kind]===take.id?'active':''} onClick={()=>onSelect(kind,take.id)} title={take.createdAt||take.label}><strong>{index+1}</strong><small>{take.provider||kind}</small></button>)}</div></div>;
}

function SceneActions({scene,index,count,onAction,onInsert,c}){
  const [open,setOpen]=useState(false),act=async(action,extra={})=>{setOpen(false);await onAction(scene.id,{action,...extra});};
  const remove=async()=>{if(window.confirm(c.removeSceneConfirm))await act('remove');};
  return <div className="scene-actions" onClick={(event)=>event.stopPropagation()}><button className="scene-more" aria-label={c.structure} onClick={()=>setOpen((value)=>!value)}><MoreHorizontal/></button>{open&&<div className="scene-actions-menu"><button disabled={index===0} onClick={()=>act('move',{direction:'up'})}><ArrowUp/>{c.moveUp}</button><button disabled={index===count-1} onClick={()=>act('move',{direction:'down'})}><ArrowDown/>{c.moveDown}</button><button onClick={()=>act('split')}><Scissors/>{c.splitScene}</button><button onClick={()=>act('duplicate')}><Copy/>{c.duplicateScene}</button><button disabled={index===count-1} onClick={()=>act('merge-next')}><Merge/>{c.mergeNext}</button><button onClick={()=>{setOpen(false);onInsert(scene.id);}}><Plus/>{c.addAfter}</button><button className="danger" disabled={count===1} onClick={remove}><Trash2/>{c.removeScene}</button></div>}</div>;
}

function Storyboard({project,selectedId,onSelect,onAction,onInsert,c}){
  return <aside className="director-storyboard"><header><div><span>{c.storyboard}</span><strong>{project.scenes.length} {c.scenes}</strong></div><button aria-label={c.addScene} onClick={()=>onInsert(selectedId)}><Plus/></button></header><div className="storyboard-list">{project.scenes.map((scene,index)=>{const health=sceneHealth(scene,c,!!project.artifacts?.final);return <article key={scene.id} className={`storyboard-card ${scene.id===selectedId?'active':''}`} onClick={()=>onSelect(scene.id)}><div className="storyboard-thumb">{scene.artifacts?.visual?<img src={mediaUrl(project,scene,'visual')} alt=""/>:<span>{String(index+1).padStart(2,'0')}</span>}{scene.artifacts?.clip&&<i><Film/></i>}</div><div className="storyboard-copy"><div><span>SC {String(index+1).padStart(2,'0')}</span><small>{(scene.durationMs/1000).toFixed(1)}s</small></div><strong>{scene.text}</strong><footer><em className={health.tone}/><span>{health.label}</span><div>{STAGES.map((stage)=><i key={stage} className={scene.review?.[stage]||'pending'}/>)}</div></footer></div><SceneActions scene={scene} index={index} count={project.scenes.length} onAction={onAction} onInsert={onInsert} c={c}/></article>;})}</div><button className="storyboard-add" onClick={()=>onInsert(project.scenes.at(-1)?.id)}><Plus/><span>{c.addScene}</span></button></aside>;
}

function Impact({items,c}){return items?.length?<div className="director-impact"><span>{c.affected}</span><div>{items.map((stage)=><em key={stage}>{stage==='final'?c.finalFilm:labels(c)[stage]}</em>)}</div></div>:null;}

function JobProgress({job,onCancel,c}){
  const remaining=job.progress?.estimatedRemainingMs,seconds=remaining==null?null:Math.max(0,Math.round(remaining/1000));
  const stageMessages={voice:c.jobVoice,visual:c.jobVisual,render:c.jobRender,clip:c.jobClip,final:c.jobFinal,'visual-qa':c.jobVisualQa,'audio-qa':c.jobAudioQa,'repair-voice':c.jobRepairVoice,'repair-visual':c.jobRepairVisual};
  const sceneNumber=job.progress?.sceneId?.match(/(\d+)$/)?.[1],message=job.status==='queued'?c.jobQueued:job.status==='cancelling'?c.stopping:stageMessages[job.progress?.stage]||c.jobWorking;
  return <div className="active-job"><div><span><LoaderCircle className="spin"/>{message}{sceneNumber?` · SC ${sceneNumber}`:''}</span><strong>{job.progress?.percent||0}%{seconds!==null?` · ~${seconds}s`:''}</strong></div><i><b style={{width:`${job.progress?.percent||0}%`}}/></i><button onClick={()=>onCancel(job.id)} disabled={job.status==='cancelling'}><Square/>{job.status==='cancelling'?c.stopping:c.stop}</button></div>;
}

function QualityCheckList({section,c}){
  if(!section)return <p className="quality-empty">{c.qaNotRun}</p>;
  return <div className="quality-checks">{Object.entries(section.checks||{}).map(([key,item])=><div key={key} className={item.status}><i>{item.status==='pass'?<Check/>:item.status==='unchecked'?<MoreHorizontal/>:<AlertTriangle/>}</i><span><strong>{item.label||key}</strong><small>{item.note}</small></span></div>)}</div>;
}

function BrollSearchPanel({scene,providers,onSearch,onSelect,running,c}){
  const available=providers?.names||['pexels','pixabay'];
  const preferred=available.find((name)=>providers?.configured?.[name])||available[0]||'pexels';
  const [provider,setProvider]=useState(preferred),[query,setQuery]=useState(scene.visualIntent||scene.text||''),[items,setItems]=useState([]),[searching,setSearching]=useState(false),[selecting,setSelecting]=useState(''),[message,setMessage]=useState(''),[startMs,setStartMs]=useState(scene.brollStartMs||0);
  useEffect(()=>{setQuery(scene.visualIntent||scene.text||'');setItems([]);setMessage('');setStartMs(scene.brollStartMs||0);},[scene.id]);
  const search=async(event)=>{event.preventDefault();if(!query.trim())return;setSearching(true);setMessage('');try{const result=await onSearch({provider,query:query.trim(),orientation:'portrait'});setItems(result.items||[]);if(!result.items?.length)setMessage(c.brollNoResults);}catch(error){setMessage(error.message);}finally{setSearching(false);}};
  const choose=async(item)=>{setSelecting(item.id);setMessage('');try{if(await onSelect(scene.id,item,Number(startMs)||0))setMessage(c.brollSelected);}catch(error){setMessage(error.message);}finally{setSelecting('');}};
  return <section className="broll-search-panel"><header><span><Film/>{c.brollLibrary}</span>{scene.broll&&<small>{scene.broll}</small>}</header>{scene.brollSource&&<p className="broll-current">{scene.brollSource.attribution||`${scene.brollSource.provider} · ${scene.brollSource.creator||''}`} {scene.brollSource.sourceUrl&&<a href={scene.brollSource.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink/>{c.source}</a>}</p>}<form onSubmit={search}><Select value={provider} onValueChange={setProvider}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{available.map((name)=><SelectItem key={name} value={name}>{name[0].toUpperCase()+name.slice(1)}{providers?.configured?.[name]?'':' · no key'}</SelectItem>)}</SelectContent></Select><Input value={query} onChange={(event)=>setQuery(event.target.value)} maxLength={100} placeholder={c.brollSearchPlaceholder}/><Button type="submit" variant="outline" disabled={searching||running||!query.trim()}>{searching?<LoaderCircle className="spin"/>:<Search/>}{c.search}</Button></form><label className="broll-offset"><span>{c.brollStart}</span><Input type="number" min="0" step="100" value={startMs} onChange={(event)=>setStartMs(event.target.value)}/><small>ms</small></label>{message&&<p className="broll-message">{message}</p>}<div className="broll-results">{items.map((item)=><article key={`${item.provider}-${item.id}`}><div>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt="" loading="lazy"/>:<Film/>}<span>{item.width&&item.height?`${item.width}×${item.height}`:''}{item.durationSec?` · ${item.durationSec}s`:''}</span></div><p>{item.attribution}</p><footer>{item.sourceUrl?<a href={item.sourceUrl} target="_blank" rel="noreferrer">{c.viewSource}<ExternalLink/></a>:<span/>}<Button size="sm" disabled={!!selecting||running} onClick={()=>choose(item)}>{selecting===item.id?<LoaderCircle className="spin"/>:<Download/>}{c.useBroll}</Button></footer></article>)}</div></section>;
}

function DrawRevealArtworkPanel({project,scene,onUpload,onLoadPath,onSavePath,running,c}){
  const inputRef=useRef(null),[uploading,setUploading]=useState(false),[editingPath,setEditingPath]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>setMessage(''),[scene.id]);
  const choose=async(event)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)){setMessage(c.artworkTypeError);return;}if(file.size>25*1024*1024){setMessage(c.artworkSizeError);return;}setUploading(true);setMessage('');try{await onUpload(scene.id,file);setMessage(c.artworkUploaded);}catch(error){setMessage(error.message);}finally{setUploading(false);}};
  const customPoints=scene.drawReveal?.path?.length;
  return <section className="artwork-upload-panel"><header><span><ImageIcon/>{c.drawRevealArtwork}</span>{scene.artwork&&<small>{scene.artwork}</small>}</header>{scene.artwork&&<img src={mediaUrl(project,scene,'artwork')} alt={c.drawRevealArtwork}/>}<p>{customPoints?`${c.customDrawPath} · ${customPoints} ${c.points}`:c.contourAutoPath}</p><input ref={inputRef} type="file" accept="image/png,image/jpeg,.png,.jpg,.jpeg" onChange={choose}/><div className="artwork-actions"><Button type="button" variant="outline" disabled={running||uploading} onClick={()=>inputRef.current?.click()}>{uploading?<LoaderCircle className="spin"/>:<Upload/>}{scene.artwork?c.replaceArtwork:c.chooseArtwork}</Button>{scene.artwork&&<Button type="button" variant="outline" disabled={running} onClick={()=>setEditingPath((value)=>!value)}><WandSparkles/>{c.editDrawPath}</Button>}</div>{message&&<small className="artwork-message">{message}</small>}{editingPath&&scene.artwork&&<DrawRevealPathEditor project={project} scene={scene} running={running} onLoad={onLoadPath} onSave={onSavePath} onClose={()=>setEditingPath(false)} c={c}/>}</section>;
}

function RoughCutDialog({open,onOpenChange,project,onLoad,onGenerate,running,c}){
  const [manifest,setManifest]=useState(null),[index,setIndex]=useState(0),[loading,setLoading]=useState(false);
  useEffect(()=>{if(!open)return;setLoading(true);onLoad().then((value)=>{setManifest(value);setIndex(0);}).finally(()=>setLoading(false));},[open,project.updatedAt]);
  const playable=manifest?.scenes.filter((scene)=>scene.clip)||[],active=playable[index];
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="rough-cut-dialog"><DialogHeader><DialogTitle>{c.roughCutPlayer}</DialogTitle><DialogDescription>{manifest?`${manifest.readyScenes}/${manifest.scenes.length} ${c.scenesReady}`:project.title}</DialogDescription></DialogHeader>{loading?<div className="rough-loading"><LoaderCircle className="spin"/></div>:active?<><video key={active.id} controls autoPlay preload="metadata" src={`${active.clip}?v=${encodeURIComponent(project.updatedAt||'current')}`} onEnded={()=>setIndex((value)=>Math.min(playable.length-1,value+1))}/><div className="rough-transport"><button disabled={index===0} onClick={()=>setIndex(index-1)}><ArrowLeft/></button><span><strong>{active.index+1}. {active.text}</strong><small>{index+1}/{playable.length}</small></span><button disabled={index===playable.length-1} onClick={()=>setIndex(index+1)}><ArrowRight/></button></div></>:<div className="rough-empty"><Film/><h3>{c.noRoughCut}</h3><p>{c.noRoughCutBody}</p><Button disabled={running} onClick={async()=>{if(await onGenerate())onOpenChange(false);}}><WandSparkles/>{c.generateRoughCut}</Button></div>}</DialogContent></Dialog>;
}

export default function DirectorWorkspace({project,running,keyboardLocked=false,activeJob,command,onContextChange,onCancelJob,onUndo,onRedo,onSelectTake,onRunQuality,onGetRepairPlan,onApplyRepairs,onSave,onRunStage,onReview,onReviewBulk,onRunAll,onLoadRoughCut,onUpdateProject,onSceneAction,onInsertScene,onDirectorPlan,onSearchBroll,onSelectBroll,onUploadArtwork,onLoadDrawRevealPath,onSaveDrawRevealPath,brollProviders,rendererNames,c}){
  const [selectedId,setSelectedId]=useState(project.scenes[0]?.id),[view,setView]=useState('best'),[panel,setPanel]=useState('director');
  const [text,setText]=useState(''),[visualIntent,setVisualIntent]=useState(''),[instruction,setInstruction]=useState(''),[proposal,setProposal]=useState(null),[directing,setDirecting]=useState(false),[directorError,setDirectorError]=useState('');
  const [finalOpen,setFinalOpen]=useState(false),[roughOpen,setRoughOpen]=useState(false),[repairPlan,setRepairPlan]=useState(null),[memory,setMemory]=useState({characters:'',palette:'',artDirection:'',pronunciations:''});
  const [layout,setLayout]=usePersistentState('cutroom.workspace.layout.v1',{storyboardWidth:280,panelWidth:340,storyboardCollapsed:false,panelCollapsed:false,focus:false});
  const [drag,setDrag]=useState(null),roomRef=useRef(null);
  const scene=project.scenes.find((item)=>item.id===selectedId)||project.scenes[0],sceneIndex=project.scenes.findIndex((item)=>item.id===scene?.id),totalMs=project.scenes.reduce((sum,item)=>sum+item.durationMs,0);
  const completed=project.scenes.filter((item)=>item.review?.clip==='approved'||project.artifacts?.final&&item.artifacts?.clip).length,progress=Math.round(completed/Math.max(1,project.scenes.length)*100),scriptApproved=project.scenes.length>0&&project.scenes.every((item)=>item.review?.script==='approved');
  const next=useMemo(()=>{const hasFinal=!!project.artifacts?.final,own=nextForScene(scene,c,hasFinal);if(own)return {...own,sceneId:scene.id};for(const item of project.scenes){const action=nextForScene(item,c,hasFinal);if(action)return {...action,sceneId:item.id};}return project.artifacts?.final?null:{kind:'final',title:c.exportFinal,titleAction:c.export,body:c.exportFinalBody};},[project,scene,c]);
  const inbox=useMemo(()=>buildActionInbox(project,c),[project,c]);
  useEffect(()=>{if(!project.scenes.some((item)=>item.id===selectedId))setSelectedId(project.scenes[0]?.id);},[project.scenes,selectedId]);
  useEffect(()=>{setText(scene?.text||'');setVisualIntent(scene?.visualIntent||scene?.text||'');setProposal(null);setDirectorError('');},[scene?.id,scene?.text,scene?.visualIntent]);
  useEffect(()=>setMemory({characters:(project.memory?.characters||[]).join('\n'),palette:(project.memory?.palette||[]).join(', '),artDirection:project.memory?.artDirection||'',pronunciations:(project.memory?.pronunciations||[]).join('\n')}),[project.memory]);
  useEffect(()=>{if(!drag)return;const move=(event)=>setLayout((value)=>({...value,[drag.side==='storyboard'?'storyboardWidth':'panelWidth']:Math.max(drag.side==='storyboard'?210:280,Math.min(drag.side==='storyboard'?430:520,drag.start+(drag.side==='storyboard'?event.clientX-drag.x:drag.x-event.clientX)))}));const stop=()=>setDrag(null);window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop,{once:true});return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);};},[drag,setLayout]);
  useEffect(()=>{if(scene)onContextChange?.({sceneId:scene.id,view:view==='best'?bestView(scene):view,panel,focus:layout.focus});},[scene?.id,view,panel,layout.focus,onContextChange]);
  useEffect(()=>{if(!command||!scene)return;if(command.type==='scene'&&project.scenes.some((item)=>item.id===command.sceneId)){setSelectedId(command.sceneId);setView('best');}if(command.type==='view'&&VIEWS.includes(command.view))setView(command.view);if(command.type==='focus')setLayout((value)=>({...value,focus:!value.focus}));},[command?.id]);
  useEffect(()=>{if(!scene||keyboardLocked||roughOpen||finalOpen)return;const keydown=(event)=>{const target=event.target,editing=['INPUT','TEXTAREA','SELECT'].includes(target?.tagName)||target?.isContentEditable;const key=event.key.toLowerCase();if((event.metaKey||event.ctrlKey)&&key==='s'){event.preventDefault();if(!running&&(text!==scene.text||visualIntent!==(scene.visualIntent||scene.text)))onSave(scene.id,{text,visualIntent});return;}if(editing||event.metaKey||event.ctrlKey||event.altKey)return;if(key==='j'||key==='k'){event.preventDefault();const nextIndex=Math.max(0,Math.min(project.scenes.length-1,sceneIndex+(key==='j'?1:-1)));setSelectedId(project.scenes[nextIndex].id);setView('best');return;}if(['1','2','3','4'].includes(key)){event.preventDefault();setView(STAGES[Number(key)-1]);return;}if(key===' '){const media=roomRef.current?.querySelector('.director-preview video, .director-preview audio');if(media){event.preventDefault();media.paused?media.play():media.pause();}return;}const stage=view==='best'?bestView(scene):view;if(key==='a'&&!running&&ready(scene,stage)){event.preventDefault();onReview(scene.id,stage,'approved');}if(key==='r'&&!running){event.preventDefault();if(['voice','visual','clip'].includes(stage))onRunStage(scene.id,stage);else{setPanel('edit');setView('script');}}if(key==='f'){event.preventDefault();setLayout((value)=>({...value,focus:!value.focus}));}};window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown);},[scene,sceneIndex,project.scenes,view,text,visualIntent,running,keyboardLocked,roughOpen,finalOpen,onSave,onReview,onRunStage,setLayout]);
  if(!scene)return null;
  const dirty=text!==scene.text||visualIntent!==(scene.visualIntent||scene.text),health=sceneHealth(scene,c,!!project.artifacts?.final),history=project.history||{undo:[],redo:[]};
  const selectScene=(id)=>{setSelectedId(id);setView('best');},sceneAction=async(id,payload)=>{const result=await onSceneAction(id,payload);if(result?.selectedSceneId)setSelectedId(result.selectedSceneId);return result;};
  const insert=async(afterSceneId)=>{const result=await onInsertScene(afterSceneId);if(result?.selectedSceneId){setSelectedId(result.selectedSceneId);setPanel('edit');setView('script');}return result;};
  const runNext=async()=>{if(!next)return;if(next.sceneId&&next.sceneId!==scene.id)setSelectedId(next.sceneId);if(next.kind==='edit'){setPanel('edit');setView(next.stage);return;}if(next.kind==='quality'){setPanel('quality');setView('best');return;}if(next.kind==='review')return onReview(next.sceneId||scene.id,next.stage,'approved');if(next.kind==='run')return onRunStage(next.sceneId||scene.id,next.stage);if(next.kind==='final')return onRunAll({stage:'final'});};
  const runAll=async()=>{if(running)return false;const switched=project.settings?.workflowMode==='auto'||await onUpdateProject({workflowMode:'auto'});return switched?onRunAll({stage:'all'}):false;};
  const approveScriptAndRun=async()=>{if(running||!onReviewBulk)return;const sceneIds=project.scenes.map((item)=>item.id);if(!sceneIds.length)return;const reviewed=await onReviewBulk('script',sceneIds,'approved');if(reviewed)await runAll();};
  const askDirector=async(event)=>{event.preventDefault();if(!instruction.trim())return;setDirecting(true);setDirectorError('');try{setProposal(await onDirectorPlan(scene.id,instruction));}catch(error){setDirectorError(error.message);}finally{setDirecting(false);}};
  const applyProposal=async()=>{if(!proposal)return;setDirecting(true);setDirectorError('');try{let applied=true;if(proposal.action==='update_scene')applied=await onSave(scene.id,Object.fromEntries(Object.entries(proposal.changes||{}).filter(([,value])=>typeof value==='string')));else if(proposal.action==='split_scene')applied=await sceneAction(scene.id,{action:'split'});else if(proposal.action==='regenerate_visual')applied=await onRunStage(scene.id,'visual');else if(proposal.action==='regenerate_voice')applied=await onRunStage(scene.id,'voice');else if(proposal.action==='regenerate_clip')applied=await onRunStage(scene.id,'clip');if(applied){setProposal(null);setInstruction('');}}catch(error){setDirectorError(error.message);}finally{setDirecting(false);}};
  const save=async()=>{if(await onSave(scene.id,{text,visualIntent}))setPanel('director');};
  const saveMemory=()=>onUpdateProject({memory:{characters:memory.characters.split('\n').map((item)=>item.trim()).filter(Boolean),palette:memory.palette.split(',').map((item)=>item.trim()).filter(Boolean),artDirection:memory.artDirection,pronunciations:memory.pronunciations.split('\n').map((item)=>item.trim()).filter(Boolean)}});
  const generateRoughCut=runAll;
  const loadRepairs=async()=>setRepairPlan(await onGetRepairPlan()),rendererOptions=rendererNames.map((name)=><SelectItem key={name} value={name}>{c[name]||name}</SelectItem>);
  const resizePanel=(side,delta)=>setLayout((value)=>({...value,[side==='storyboard'?'storyboardWidth':'panelWidth']:Math.max(side==='storyboard'?210:280,Math.min(side==='storyboard'?430:520,value[side==='storyboard'?'storyboardWidth':'panelWidth']+delta))}));
  const startResize=(side,event)=>{event.preventDefault();setDrag({side,x:event.clientX,start:side==='storyboard'?layout.storyboardWidth:layout.panelWidth});};
  const resizeWithKeyboard=(side,event)=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();const direction=event.key==='ArrowRight'?1:-1;resizePanel(side,(side==='storyboard'?direction:-direction)*16);};
  const openInboxItem=(item)=>{setSelectedId(item.sceneId);setView(item.stage||'best');setPanel(item.kind==='edit'?'edit':item.kind==='quality'?'quality':'director');};

  return <section ref={roomRef} className={`director-room ${activeJob?'has-job':''} ${layout.focus?'focus-mode':''}`}>
    {layout.focus&&<button className="focus-exit" onClick={()=>setLayout((value)=>({...value,focus:false}))} title={`${c.exitFocus} · F`}><Minimize2/><span>{c.exitFocus}</span><kbd>F</kbd></button>}
    <header className="director-project-header"><div className="director-project-title"><span><Clapperboard/> {c.directingRoom}</span><h1>{project.title}</h1><p>{project.scenes.length} {c.scenes} · {(totalMs/60000).toFixed(1)} min · {project.settings?.format==='short'?'9:16':'16:9'}</p></div><div className="director-project-progress"><div><span>{c.projectProgress}</span><strong>{progress}%</strong></div><i><b style={{width:`${progress}%`}}/></i></div><div className="director-project-actions"><div className="history-buttons"><button title={c.undo} disabled={running||!history.undo.length} onClick={onUndo}><Undo2/></button><button title={c.redo} disabled={running||!history.redo.length} onClick={onRedo}><Redo2/></button></div><Select value={project.settings?.workflowMode||'studio'} onValueChange={(workflowMode)=>onUpdateProject({workflowMode})} disabled={running}><SelectTrigger aria-label={c.workflowMode}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="studio">{c.controlled}</SelectItem><SelectItem value="auto">{c.autopilot}</SelectItem></SelectContent></Select>{!scriptApproved?<Button className="bulk-pipeline-action" disabled={running} onClick={approveScriptAndRun}><CheckCircle2/>{c.approveScriptAndRun}</Button>:<Button className="bulk-pipeline-action" disabled={running} onClick={runAll}><Play/>{c.runPipeline}</Button>}<Button variant="outline" onClick={()=>setRoughOpen(true)}><Play/>{c.roughCut}</Button>{project.artifacts?.final&&<Button variant="outline" onClick={()=>setFinalOpen(true)}><Eye/>{c.watchFinal}</Button>}</div>{activeJob&&<JobProgress job={activeJob} onCancel={onCancelJob} c={c}/>}</header>
    <div className={`director-grid ${layout.storyboardCollapsed?'storyboard-collapsed':''} ${layout.panelCollapsed?'panel-collapsed':''}`} style={{'--storyboard-width':`${layout.storyboardWidth}px`,'--director-panel-width':`${layout.panelWidth}px`}}><Storyboard project={project} selectedId={scene.id} onSelect={selectScene} onAction={sceneAction} onInsert={insert} c={c}/><div className="director-resizer storyboard-resizer" role="separator" aria-orientation="vertical" aria-label={c.resizeStoryboard} aria-valuemin="210" aria-valuemax="430" aria-valuenow={layout.storyboardWidth} tabIndex={0} onKeyDown={(event)=>resizeWithKeyboard('storyboard',event)} onPointerDown={(event)=>startResize('storyboard',event)}/><main className="director-stage"><header className="director-stage-head"><div><span>SCENE {String(sceneIndex+1).padStart(2,'0')}</span><strong>{view==='best'?c.bestAvailable:labels(c)[view]}</strong></div><div className="stage-head-actions"><Badge className={`health-${health.tone}`} variant="outline">{health.label}</Badge><button title={layout.storyboardCollapsed?c.showStoryboard:c.hideStoryboard} onClick={()=>setLayout((value)=>({...value,storyboardCollapsed:!value.storyboardCollapsed}))}>{layout.storyboardCollapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><button title={`${layout.focus?c.exitFocus:c.focusPreview} · F`} onClick={()=>setLayout((value)=>({...value,focus:!value.focus}))}>{layout.focus?<Minimize2/>:<Maximize2/>}</button><button title={layout.panelCollapsed?c.showDirector:c.hideDirector} onClick={()=>setLayout((value)=>({...value,panelCollapsed:!value.panelCollapsed}))}>{layout.panelCollapsed?<PanelRightOpen/>:<PanelRightClose/>}</button></div></header><nav className="director-view-tabs" aria-label={c.selectView}>{VIEWS.map((item)=><button key={item} className={view===item?'active':''} onClick={()=>setView(item)}>{item==='best'?<Sparkles/>:<StageIcon stage={item}/>}<span>{labels(c)[item]}</span></button>)}</nav><div className={`director-preview format-${project.settings?.format||'landscape'}`}><Preview project={project} scene={scene} view={view} c={c}/><TakeSwitcher scene={scene} view={view} c={c} onSelect={(kind,takeId)=>onSelectTake(scene.id,kind,takeId)}/></div><footer className="director-pager"><button disabled={sceneIndex===0} onClick={()=>selectScene(project.scenes[sceneIndex-1].id)}><ArrowLeft/>{c.previousScene}</button><div><strong>{sceneIndex+1}</strong><span>/ {project.scenes.length}</span></div><button disabled={sceneIndex===project.scenes.length-1} onClick={()=>selectScene(project.scenes[sceneIndex+1].id)}>{c.nextScene}<ArrowRight/></button></footer></main><div className="director-resizer panel-resizer" role="separator" aria-orientation="vertical" aria-label={c.resizeDirector} aria-valuemin="280" aria-valuemax="520" aria-valuenow={layout.panelWidth} tabIndex={0} onKeyDown={(event)=>resizeWithKeyboard('panel',event)} onPointerDown={(event)=>startResize('panel',event)}/>
      <aside className="director-panel"><nav><button className={panel==='director'?'active':''} onClick={()=>setPanel('director')}><Bot/>{c.director}</button><button className={panel==='edit'?'active':''} onClick={()=>setPanel('edit')}><Layers3/>{c.editScene}</button><button className={panel==='quality'?'active':''} onClick={()=>setPanel('quality')}><Gauge/>{c.quality}</button><button className={panel==='memory'?'active':''} onClick={()=>setPanel('memory')}><BrainCircuit/>{c.memory}</button></nav>
        {panel==='director'?<div className="director-panel-body"><section className="next-action-card"><span><Zap/>{c.nextMove}</span>{next?<><h2>{next.title}</h2><p>{next.body}</p><Button disabled={running} onClick={runNext}>{running?<LoaderCircle className="spin"/>:next.kind==='review'?<Check/>:next.kind==='edit'?<FileText/>:next.kind==='quality'?<Gauge/>:next.kind==='final'?<Clapperboard/>:<RefreshCw/>}{next.titleAction||c.open}</Button></>:<><h2>{c.allReady}</h2><p>{c.allReadyBody}</p><CheckCircle2 className="all-ready-mark"/></>}</section><section className="action-inbox"><header><span><Inbox/>{c.actionInbox}</span><Badge variant="outline">{inbox.length}</Badge></header>{inbox.length?<div>{inbox.slice(0,12).map((item)=><button key={`${item.sceneId}-${item.stage}-${item.kind}`} onClick={()=>openInboxItem(item)}><i className={item.health.tone}>{item.index+1}</i><span><strong>{item.title}</strong><small>{item.body}</small><em>{item.estimate.time} · {item.estimate.cost}</em></span><ArrowRight/></button>)}</div>:<p>{c.actionInboxEmpty}</p>}</section><section className="director-command"><header><span><Sparkles/>{c.director}</span><Badge variant="outline">SC {String(sceneIndex+1).padStart(2,'0')}</Badge></header><form onSubmit={askDirector}><Textarea value={instruction} onChange={(event)=>setInstruction(event.target.value)} rows={4} placeholder={c.directorPlaceholder}/><div className="director-suggestions"><button type="button" onClick={()=>setInstruction(c.visualSuggestion)}>{c.visualSuggestion}</button><button type="button" onClick={()=>setInstruction(c.regenerateSuggestion)}>{c.regenerateSuggestion}</button><button type="button" onClick={()=>setInstruction(c.splitSuggestion)}>{c.splitSuggestion}</button></div><Button type="submit" disabled={directing||!instruction.trim()}>{directing?<LoaderCircle className="spin"/>:<Send/>}{c.prepareProposal}</Button></form></section>{directorError&&<div className="director-inline-error"><AlertTriangle/><span>{directorError}</span></div>}{proposal&&<section className="director-proposal"><header><span>{c.proposal}</span><button onClick={()=>setProposal(null)}><X/></button></header><h3>{proposal.summary}</h3><p>{proposal.note}</p><Impact items={proposal.impact} c={c}/><footer><Button variant="ghost" onClick={()=>setProposal(null)}>{c.discard}</Button><Button disabled={directing||proposal.action==='noop'} onClick={applyProposal}>{directing?<LoaderCircle className="spin"/>:<Check/>}{c.apply}</Button></footer></section>}</div>
        :panel==='edit'?<div className="director-panel-body edit-panel"><section><div className="field-title"><span>{c.narration}</span><small>{text.length} {c.chars}</small></div><Textarea value={text} onChange={(event)=>setText(event.target.value)} rows={8}/></section><section><div className="field-title"><span>{c.visualIntent}</span><small>{c.visualIntentHint}</small></div><Textarea value={visualIntent} onChange={(event)=>setVisualIntent(event.target.value)} rows={6}/></section>{(scene.renderer||project.settings?.renderer)==='cinematic-broll'&&<BrollSearchPanel scene={scene} providers={brollProviders} onSearch={onSearchBroll} onSelect={onSelectBroll} running={running} c={c}/>} {(scene.renderer||project.settings?.renderer)==='draw-reveal'&&<DrawRevealArtworkPanel project={project} scene={scene} onUpload={onUploadArtwork} onLoadPath={onLoadDrawRevealPath} onSavePath={onSaveDrawRevealPath} running={running} c={c}/>}<details className="director-advanced"><summary>{c.advanced}</summary><label><span>{c.videoFormat}</span><Select value={project.settings?.format||'landscape'} onValueChange={(format)=>onUpdateProject({format})} disabled={running}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="landscape">16:9</SelectItem><SelectItem value="short">9:16</SelectItem></SelectContent></Select></label><label><span>{c.projectRenderer}</span><Select value={project.settings?.renderer} onValueChange={(renderer)=>onUpdateProject({renderer})} disabled={running}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{rendererOptions}</SelectContent></Select></label><label><span>{c.sceneRendererHint}</span><Select value={scene.renderer||project.settings?.renderer} onValueChange={(renderer)=>onSave(scene.id,{renderer})} disabled={running}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{rendererOptions}</SelectContent></Select></label><label><span>{c.technicalPrompt}</span><Textarea value={scene.visualPrompt||''} readOnly rows={5}/></label></details><div className="edit-save"><p>{dirty?c.unsavedImpact:c.noUnsavedChanges}</p><Button disabled={running||!dirty} onClick={save}><Save/>{c.saveChanges}</Button></div></div>
        :panel==='quality'?<div className="director-panel-body quality-panel"><header><span><Activity/>{c.qualityControl}</span><Badge className={`quality-${scene.quality?.status||'unchecked'}`}>{({pass:c.qaPass,warn:c.qaWarn,fail:c.qaFail,unchecked:c.notChecked})[scene.quality?.status||'unchecked']}</Badge></header><section><h3><ImageIcon/>{c.visualChecks}</h3><QualityCheckList section={scene.quality?.visual} c={c}/></section><section><h3><AudioLines/>{c.audioChecks}</h3><QualityCheckList section={scene.quality?.audio} c={c}/></section><div className="quality-actions"><Button variant="outline" disabled={running} onClick={()=>onRunQuality([scene.id])}><Gauge/>{c.checkScene}</Button><Button disabled={running} onClick={()=>onRunQuality()}><Activity/>{c.checkAll}</Button><Button variant="ghost" disabled={running} onClick={loadRepairs}><WandSparkles/>{c.planRepairs}</Button></div>{repairPlan&&<section className="repair-plan"><header><span>{c.repairProposal}</span><strong>{repairPlan.sceneCount} {c.scenes}</strong></header>{repairPlan.actions.length?<><div>{repairPlan.actions.map((item)=><p key={`${item.sceneId}-${item.stage}`}><span>{item.sceneId}</span><strong>{labels(c)[item.stage]}</strong><small>{item.reason}</small></p>)}</div><footer><span>{repairPlan.cost.imageRequests} {c.imageRequests} · {repairPlan.cost.voiceRequests} {c.voiceRequests} · {repairPlan.cost.renders} {c.downstreamRenders}</span><Button disabled={running} onClick={()=>onApplyRepairs(repairPlan.actions)}>{c.applyRepairs}</Button></footer></>:<p className="quality-empty">{c.noRepairs}</p>}</section>}</div>
        :<div className="director-panel-body memory-panel"><header><span><BrainCircuit/>{c.projectMemory}</span><p>{c.projectMemoryBody}</p></header><label><span><Palette/>{c.artDirection}</span><Textarea rows={5} value={memory.artDirection} onChange={(event)=>setMemory((value)=>({...value,artDirection:event.target.value}))}/></label><label><span>{c.recurringCharacters}</span><Textarea rows={4} value={memory.characters} onChange={(event)=>setMemory((value)=>({...value,characters:event.target.value}))} placeholder={c.onePerLine}/></label><label><span>{c.palette}</span><Input value={memory.palette} onChange={(event)=>setMemory((value)=>({...value,palette:event.target.value}))} placeholder="#E85D3A, ink, warm paper"/></label><label><span>{c.pronunciations}</span><Textarea rows={4} value={memory.pronunciations} onChange={(event)=>setMemory((value)=>({...value,pronunciations:event.target.value}))} placeholder="CUTROOM = cut room"/></label><Button disabled={running} onClick={saveMemory}><Save/>{c.saveMemory}</Button><section className="history-log"><header><History/>{c.recentChanges}</header>{history.undo.slice(-5).reverse().map((entry)=><p key={entry.id}><span>{entry.label}</span><small>{entry.at?new Date(entry.at).toLocaleTimeString():''}</small></p>)}</section></div>}
      </aside>
    </div>
    <footer className="director-timeline"><div><span>{c.timeline}</span><strong>{Math.floor(totalMs/60000)}:{String(Math.round(totalMs/1000)%60).padStart(2,'0')}</strong></div><div className="timeline-track">{project.scenes.map((item,index)=>{const itemHealth=sceneHealth(item,c,!!project.artifacts?.final);return <button key={item.id} className={`${item.id===scene.id?'active':''} ${itemHealth.tone}`} style={{flexGrow:Math.max(1,item.durationMs)}} onClick={()=>selectScene(item.id)} title={`${index+1}. ${item.text}`}><span>{index+1}</span><i/></button>;})}</div></footer>
    <RoughCutDialog open={roughOpen} onOpenChange={setRoughOpen} project={project} onLoad={onLoadRoughCut} onGenerate={generateRoughCut} running={running} c={c}/>
    <Dialog open={finalOpen} onOpenChange={setFinalOpen}><DialogContent className="final-preview-dialog"><DialogHeader><DialogTitle>{c.finalFilm}</DialogTitle><DialogDescription>{project.title}</DialogDescription></DialogHeader>{project.artifacts?.final&&<video controls autoPlay preload="metadata" src={`/media/${encodeURIComponent(project.id)}/final?v=${encodeURIComponent(project.updatedAt||'current')}`}/>}</DialogContent></Dialog>
  </section>;
}
