export const UI_LANGUAGES=[
  {code:'vi',label:'Tiếng Việt'},
  {code:'en',label:'English'},
];

const en={
  brandSubtitle:'video workflow desk', systemReady:'System ready', connecting:'Connecting', localRuntime:'local runtime', refreshWorkspace:'Refresh workspace',
  productions:'Productions', newProduction:'New production', scenes:'scenes', rendered:'rendered', production:'PRODUCTION', testMode:'TEST MODE', apiConfigured:'API key configured', openaiSettings:'OpenAI settings', dismiss:'Dismiss', renderer:'Renderer', refresh:'Refresh', rendering:'Rendering…', runPipeline:'Run full pipeline',
  emptyKicker:'local-first production desk', emptyTitle:'Turn one idea into', emptyAccent:'a finished cut.', emptyBody:'Shape the script, direct each visual, render only what changed, and review the final film from one calm workspace.', createTest:'Create test project', workflow:'Workflow stages', write:'Write', illustrate:'Illustrate', voice:'Voice', render:'Render',
  awaitingRender:'Awaiting first render', visual:'Visual', renderedClip:'Rendered clip', narration:'Narration', visualDirection:'Visual direction', imagePrompt:'image prompt', chars:'chars', saveEdit:'Save edit', renderScene:'Render scene', seconds:'sec',
  workflowMode:'Workflow mode', studioMode:'Studio', studioModeBody:'Review and approve each creative stage.', autoMode:'Auto run', autoModeBody:'Generate a complete first cut end to end.', assembleFinal:'Assemble approved cut', clipsApproved:'clips approved', scriptStage:'Script', voiceStage:'Voice', visualStage:'Visual', clipStage:'Clip', generate:'Generate', regenerate:'Regenerate', approve:'Approve', requestChanges:'Request changes',
  sceneNavigator:'Scenes', inspector:'Inspector', previousScene:'Previous', nextScene:'Next', approveNext:'Approve & next', awaitingStage:'Nothing generated for this stage yet', mockVisualReady:'Mock visual is ready for review', voiceInspectorBody:'Review delivery and timing in the center preview. Regenerate when the narration needs a different performance.', clipInspectorBody:'Review the synchronized scene cut before approving it for the final assembly.',
  byScene:'Scene', byStage:'Stage', nextTask:'Next task', bulkActions:'Bulk', generateEligible:'Generate eligible', approveReady:'Approve ready',
  newIndex:'NEW / 001', startProduction:'Start a production', startDescription:'Bring a topic, a finished script, or timed subtitles. Every scene stays independently editable and renderable.', projectTitle:'Project title', titlePlaceholder:'The habit loop', startingPoint:'Starting point', topicAuto:'Topic → auto script', preparedScript:'Prepared script', srtSubtitles:'SRT subtitles', explainPrompt:'What should the film explain?', pasteSrt:'Paste SRT subtitles', pasteScript:'Paste narration script', topicPlaceholder:'Why tiny habits compound over time', scriptPlaceholder:'Begin with the idea you want viewers to remember…', renderStyle:'Render style', whiteboard:'Whiteboard draw', simple:'Simple motion', rendererHint:'Saved with this project; you can change it later.', contentLanguage:'Video language', targetLength:'Target length', minutes:'minutes', cancel:'Cancel', createProduction:'Create production',
  lastRunStopped:'Last run stopped', masterCut:'MASTER CUT', finalFilm:'Final film', finalBody:'The latest approved scene renders, joined and ready for review.', masterPending:'Master cut pending', masterPendingBody:'Render the full pipeline after reviewing your scenes.', sceneDesk:'SCENE DESK', directBeat:'Direct every beat.', sceneDeskBody:'Save a rewrite or re-render one scene without restarting the whole production.', subtitles:'Subtitles',
  settingsIndex:'SYSTEM / PROVIDERS', providerSettings:'Provider settings', providerDescription:'Mix replaceable text, image, and voice services for this local production desk.', loadingConfig:'Loading local configuration…', serverSecrets:'Server-side secrets', serverSecretsBody:'Provider keys are written only to the local .env file and are never returned to this browser.', useOpenAI:'Use OpenAI generation', textImageProviders:'Text and image providers', independentVoice:'Voice is selected independently, so Vivibe can run alongside OpenAI text and images.', connectionsModels:'Connections & models', connectionsBody:'Choose each provider independently. Existing scene artifacts stay cached until their provider inputs change.', languageRegion:'Language', languageRegionHint:'Interface and default language for new videos', interfaceLanguage:'Interface language', defaultVideoLanguage:'Default video language', connection:'Connection', credentialEndpoint:'Credential and API endpoint', apiKey:'API key', baseUrl:'Base URL', defaultRenderer:'Default renderer', appliedNew:'Applied when a new production is created', generationStack:'Generation stack', modelsUsed:'Models used for scripts and illustrations', scriptModel:'Script model', imageModel:'Image model', imageSize:'Image size', imageQuality:'Image quality', voiceSource:'Voice source', narrationProvider:'Provider adapter used for narration', provider:'Provider', speechModel:'Speech model', voiceDirection:'Voice direction', speed:'Speed', loadVoices:'Load voices', availableVoices:'Available voices', close:'Close', saveTest:'Save & test OpenAI', saveSettings:'Save settings', settingsSaved:'Settings saved to the local .env file.',
  review:{pending:'Waiting review',approved:'Approved','changes-requested':'Changes requested',stale:'Out of date'},
  status:{draft:'Draft',planned:'Planned','voice-ready':'Voice ready','visual-ready':'Visual ready',rendered:'Rendered',ready:'Ready',running:'Rendering',complete:'Complete',error:'Needs attention'}
};

const vi={
  ...en,
  brandSubtitle:'bàn làm video', systemReady:'Hệ thống sẵn sàng', connecting:'Đang kết nối', localRuntime:'máy cục bộ', refreshWorkspace:'Làm mới workspace',
  productions:'Dự án', newProduction:'Dự án mới', scenes:'phân cảnh', rendered:'đã render', production:'SẢN XUẤT', testMode:'CHẾ ĐỘ THỬ', apiConfigured:'Đã cấu hình API key', openaiSettings:'Cài đặt OpenAI', dismiss:'Đóng', renderer:'Bộ render', refresh:'Làm mới', rendering:'Đang render…', runPipeline:'Chạy toàn bộ quy trình',
  emptyKicker:'xưởng sản xuất local-first', emptyTitle:'Biến một ý tưởng thành', emptyAccent:'một video hoàn chỉnh.', emptyBody:'Biên tập kịch bản, chỉ đạo từng hình ảnh, chỉ render phần đã đổi và duyệt video cuối trong một không gian gọn gàng.', createTest:'Tạo dự án thử', workflow:'Các bước sản xuất', write:'Viết', illustrate:'Minh họa', voice:'Lồng tiếng', render:'Render',
  awaitingRender:'Chờ render lần đầu', visual:'Hình ảnh', renderedClip:'Clip đã render', narration:'Lời thoại', visualDirection:'Chỉ dẫn hình ảnh', imagePrompt:'prompt hình ảnh', chars:'ký tự', saveEdit:'Lưu chỉnh sửa', renderScene:'Render phân cảnh', seconds:'giây',
  workflowMode:'Chế độ quy trình', studioMode:'Studio', studioModeBody:'Duyệt và quyết định ở từng công đoạn sáng tạo.', autoMode:'Chạy tự động', autoModeBody:'Tạo nhanh bản nháp hoàn chỉnh từ đầu đến cuối.', assembleFinal:'Ghép bản đã duyệt', clipsApproved:'clip đã duyệt', scriptStage:'Kịch bản', voiceStage:'Giọng đọc', visualStage:'Hình ảnh', clipStage:'Clip', generate:'Tạo', regenerate:'Tạo lại', approve:'Duyệt', requestChanges:'Yêu cầu sửa',
  sceneNavigator:'Phân cảnh', inspector:'Biên tập', previousScene:'Cảnh trước', nextScene:'Cảnh sau', approveNext:'Duyệt & tiếp', awaitingStage:'Chưa có nội dung cho công đoạn này', mockVisualReady:'Hình mock đã sẵn sàng để duyệt', voiceInspectorBody:'Nghe cách đọc và kiểm tra nhịp ở khung preview. Tạo lại nếu lời thoại cần một cách thể hiện khác.', clipInspectorBody:'Xem lại hình và tiếng đã đồng bộ trước khi duyệt clip để ghép bản cuối.',
  byScene:'Theo cảnh', byStage:'Theo bước', nextTask:'Việc tiếp theo', bulkActions:'Hàng loạt', generateEligible:'Tạo mục đủ điều kiện', approveReady:'Duyệt mục sẵn sàng',
  newIndex:'MỚI / 001', startProduction:'Bắt đầu dự án', startDescription:'Nhập chủ đề, kịch bản hoàn chỉnh hoặc phụ đề có thời gian. Mỗi phân cảnh đều có thể sửa và render độc lập.', projectTitle:'Tên dự án', titlePlaceholder:'Vòng lặp thói quen', startingPoint:'Nội dung đầu vào', topicAuto:'Chủ đề → tự viết kịch bản', preparedScript:'Kịch bản có sẵn', srtSubtitles:'Phụ đề SRT', explainPrompt:'Video sẽ giải thích điều gì?', pasteSrt:'Dán phụ đề SRT', pasteScript:'Dán kịch bản lời thoại', topicPlaceholder:'Vì sao những thói quen nhỏ tạo nên thay đổi lớn', scriptPlaceholder:'Bắt đầu bằng ý tưởng bạn muốn người xem ghi nhớ…', renderStyle:'Kiểu render', whiteboard:'Vẽ bảng trắng', simple:'Chuyển động đơn giản', rendererHint:'Được lưu riêng cho dự án và có thể đổi sau.', contentLanguage:'Ngôn ngữ video', targetLength:'Thời lượng mục tiêu', minutes:'phút', cancel:'Hủy', createProduction:'Tạo dự án',
  lastRunStopped:'Lần chạy gần nhất đã dừng', masterCut:'BẢN VIDEO CUỐI', finalFilm:'Video hoàn chỉnh', finalBody:'Bản ghép mới nhất từ các phân cảnh đã duyệt, sẵn sàng để xem.', masterPending:'Chưa có bản video cuối', masterPendingBody:'Chạy toàn bộ quy trình sau khi duyệt các phân cảnh.', sceneDesk:'BÀN PHÂN CẢNH', directBeat:'Chỉ đạo từng nhịp.', sceneDeskBody:'Lưu phần viết lại hoặc render riêng một phân cảnh mà không phải chạy lại toàn bộ dự án.', subtitles:'Phụ đề',
  settingsIndex:'HỆ THỐNG / NHÀ CUNG CẤP', providerSettings:'Cài đặt nhà cung cấp', providerDescription:'Kết hợp linh hoạt dịch vụ văn bản, hình ảnh và giọng nói cho xưởng local này.', loadingConfig:'Đang tải cấu hình cục bộ…', serverSecrets:'Bí mật phía máy chủ', serverSecretsBody:'Khóa nhà cung cấp chỉ được ghi vào file .env cục bộ và không bao giờ trả về trình duyệt.', useOpenAI:'Dùng OpenAI để tạo nội dung', textImageProviders:'Nhà cung cấp văn bản và hình ảnh', independentVoice:'Giọng đọc được chọn độc lập, nên Vivibe có thể dùng cùng văn bản và hình ảnh OpenAI.', connectionsModels:'Kết nối & mô hình', connectionsBody:'Chọn riêng từng nhà cung cấp. Các tệp phân cảnh vẫn được cache đến khi đầu vào liên quan thay đổi.', languageRegion:'Ngôn ngữ', languageRegionHint:'Giao diện và ngôn ngữ mặc định cho video mới', interfaceLanguage:'Ngôn ngữ giao diện', defaultVideoLanguage:'Ngôn ngữ video mặc định', connection:'Kết nối', credentialEndpoint:'Thông tin xác thực và API endpoint', apiKey:'API key', baseUrl:'URL gốc', defaultRenderer:'Bộ render mặc định', appliedNew:'Áp dụng khi tạo dự án mới', generationStack:'Bộ công cụ tạo nội dung', modelsUsed:'Các mô hình dùng cho kịch bản và minh họa', scriptModel:'Mô hình kịch bản', imageModel:'Mô hình hình ảnh', imageSize:'Kích thước hình', imageQuality:'Chất lượng hình', voiceSource:'Nguồn giọng đọc', narrationProvider:'Adapter dùng để tạo lời thoại', provider:'Nhà cung cấp', speechModel:'Mô hình giọng nói', voiceDirection:'Chỉ dẫn giọng đọc', speed:'Tốc độ', loadVoices:'Tải giọng đọc', availableVoices:'Giọng đọc khả dụng', close:'Đóng', saveTest:'Lưu & thử OpenAI', saveSettings:'Lưu cài đặt', settingsSaved:'Đã lưu cài đặt vào file .env cục bộ.',
  review:{pending:'Chờ duyệt',approved:'Đã duyệt','changes-requested':'Cần chỉnh sửa',stale:'Đã lỗi thời'},
  status:{draft:'Nháp',planned:'Đã lên kế hoạch','voice-ready':'Đã có giọng đọc','visual-ready':'Đã có hình',rendered:'Đã render',ready:'Sẵn sàng',running:'Đang render',complete:'Hoàn tất',error:'Cần xử lý'}
};

export function copyFor(language){return language==='en'?en:vi;}
