import { useEffect, useState } from 'react';
import { Clapperboard, Palette, Save, Settings2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const SWATCHES=['#FFFFFF','#F5C84C','#E95D3F','#2E7D6E','#2458A6','#292725'];

export default function ProjectSettingsDialog({open,onOpenChange,project,rendererNames,onSave,running,c}) {
  const [form,setForm]=useState({format:'landscape',renderer:'simple',pen:{label:'NÉT VIỆT',color:'#FFFFFF'}});
  useEffect(()=>{if(open)setForm({format:project.settings?.format||'landscape',renderer:project.settings?.renderer||'simple',pen:{label:project.settings?.pen?.label??'NÉT VIỆT',color:project.settings?.pen?.color||'#FFFFFF'}});},[open,project.settings?.format,project.settings?.renderer,project.settings?.pen?.label,project.settings?.pen?.color]);
  const updatePen=(key,value)=>setForm((current)=>({...current,pen:{...current.pen,[key]:value}}));
  const dirty=form.format!==(project.settings?.format||'landscape')||form.renderer!==(project.settings?.renderer||'simple')||form.pen.label!==(project.settings?.pen?.label??'NÉT VIỆT')||form.pen.color!==(project.settings?.pen?.color||'#FFFFFF');
  const validColor=/^#[0-9A-F]{6}$/.test(form.pen.color);
  const save=async()=>{if(await onSave(form))onOpenChange(false);};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="project-settings-dialog"><DialogHeader><span className="project-scope"><Settings2/>{c.projectScope}</span><DialogTitle>{c.projectSettings}</DialogTitle><DialogDescription>{c.projectSettingsBody}</DialogDescription></DialogHeader><div className="project-settings-content"><section><header><Clapperboard/><span><strong>{c.projectDefaults}</strong><small>{c.projectDefaultsHint}</small></span></header><div className="project-settings-grid"><label><span>{c.videoFormat}</span><Select value={form.format} onValueChange={(format)=>setForm((current)=>({...current,format}))} disabled={running}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="landscape">16:9</SelectItem><SelectItem value="short">9:16</SelectItem></SelectContent></Select></label><label><span>{c.projectRenderer}</span><Select value={form.renderer} onValueChange={(renderer)=>setForm((current)=>({...current,renderer}))} disabled={running}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{rendererNames.map((name)=><SelectItem key={name} value={name}>{c[name]||name}</SelectItem>)}</SelectContent></Select></label></div></section><section className="project-pen-section"><header><Palette/><span><strong>{c.penAppearance}</strong><small>{c.penAppearanceHint}</small></span></header><div className="project-pen-layout"><div><div className="pen-preview" style={{'--pen-color':validColor?form.pen.color:'#FFFFFF'}}><i/><strong>{form.pen.label||c.penNoLabel}</strong></div><p>{c.penImpactHint}</p></div><div className="project-pen-fields"><label><span>{c.penLabel}</span><Input value={form.pen.label} maxLength={18} onChange={(event)=>updatePen('label',event.target.value)} placeholder="NÉT VIỆT"/></label><label><span>{c.penColor}</span><div className="pen-color-field"><input type="color" value={validColor?form.pen.color:'#FFFFFF'} onChange={(event)=>updatePen('color',event.target.value.toUpperCase())}/><Input value={form.pen.color} maxLength={7} onChange={(event)=>updatePen('color',event.target.value.toUpperCase())}/></div></label><div className="pen-swatches">{SWATCHES.map((color)=><button type="button" key={color} aria-label={`${c.penColor} ${color}`} className={form.pen.color===color?'active':''} style={{background:color}} onClick={()=>updatePen('color',color)}/>)}</div></div></div></section></div><footer><Button variant="ghost" onClick={()=>onOpenChange(false)}>{c.cancel}</Button><Button disabled={running||!dirty||!validColor} onClick={save}><Save/>{c.saveProjectSettings}</Button></footer></DialogContent></Dialog>;
}
