import fs from 'node:fs'; import path from 'node:path'; import { run } from '../../core/src/process.mjs'; import { ensureDir, writeJson } from '../../core/src/utils.mjs'; import { probeVideoSize } from '../../core/src/media.mjs';
export function whiteboardScript(cfg) { return path.join(cfg.whiteboardEngineDir,'scripts','render_stream_whiteboard.py'); }
export async function ensureWhiteboardEngine(cfg) { if (fs.existsSync(whiteboardScript(cfg))) return; if (!cfg.whiteboardAutoInstall) throw new Error(`Whiteboard engine missing: ${cfg.whiteboardEngineDir}`); ensureDir(path.dirname(cfg.whiteboardEngineDir)); await run('git',['clone','--depth','1','https://github.com/geeklee/srt-whiteboard-animation.git',cfg.whiteboardEngineDir]); const prepare = path.join(cfg.whiteboardEngineDir,'scripts','prepare_env.py'); if (fs.existsSync(prepare)) await run(cfg.pythonBin,[prepare],{cwd:cfg.whiteboardEngineDir}); }
function envPython(cfg) { const candidates = [path.join(cfg.whiteboardEngineDir,'.venv','bin','python'),path.join(cfg.whiteboardEngineDir,'venv','bin','python'),path.join(cfg.whiteboardEngineDir,'.venv','Scripts','python.exe'),path.join(cfg.whiteboardEngineDir,'venv','Scripts','python.exe')]; return candidates.find(fs.existsSync) || cfg.pythonBin; }
export async function renderWhiteboardScene({ scene, imageFile, outputFile, durationSec, cfg }) {
  if (!imageFile || !fs.existsSync(imageFile)) throw new Error(`Whiteboard renderer requires a generated image for ${scene.id}`); await ensureWhiteboardEngine(cfg);
  const {width,height}=await probeVideoSize(imageFile,cfg); const annotationFile = path.join(path.dirname(imageFile),`${scene.id}.annotation.json`); const durationMs = Math.max(1000,Math.round(durationSec*1000));
  writeJson(annotationFile,{sceneId:scene.id,canvas:{width,height},storyBasis:scene.text,sceneDurationMs:durationMs,elements:[{id:'scene-illustration',label:'full scene illustration',sequence:1,narrativeRole:'main scene',subtitle:scene.text,type:'scene',region:{x:0,y:0,width,height},reveal:{direction:'top_to_bottom',startMs:0,durationMs:Math.max(500,durationMs-500),maskPaddingPx:0,protectedRegions:[]},handPath:{start:[Math.round(width/2),0],end:[Math.round(width/2),height],easing:'easeInOut'}}]});
  const hand = path.join(cfg.whiteboardEngineDir,'assets','drawing-hand.png'); const args=[whiteboardScript(cfg),imageFile,annotationFile,outputFile]; if (fs.existsSync(hand)) args.push(hand); args.push('--ink-path','grid','--color-fill','contour-wipe','--total-ms',String(durationMs),'--pause','0'); await run(envPython(cfg),args,{cwd:cfg.whiteboardEngineDir}); return outputFile;
}
